### ISSUE TITLE
游标位置不对

### ISSUE THREAD

**Issue by qi19901212** [qinci/AndroidEdit#2]
撤销之后恢复，游标的位置没有移动

**Comment by qinci** [comment]
谢谢反馈，我看看

**Comment by ShineYang** [comment]
确实游标位置有问题，跟gif图演示的不一样。

**Comment by qinci** [comment]
具体描述一下，gif图是老的版本，新版本增加了撤销选择文字

**Comment by ShineYang** [comment]
![](http://i1.piimg.com/567571/4d9b607ec8675e79.gif)
录了个gif  参考一下
