### ISSUE TITLE
如何知道下一步不能撤销或恢复呢?

### ISSUE THREAD

**Issue by keaitao0321** [qinci/AndroidEdit#3]
我需要知道下一步能否操作来改变UI状态

**Comment by qinci** [comment]
可以在里面增加方法判断里面的撤销和恢复stack是否为空，目前没提供

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: keaitao0321 <notifications@github.com&gt;
发送时间: 2019年12月19日 10:31
收件人: qinci/AndroidEdit <AndroidEdit@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[qinci/AndroidEdit] 如何知道下一步不能撤销或恢复呢? (#3)

**Comment by keaitao0321** [comment]
好的,非常感谢!
 /**
     * 可以恢复
     *
     * @return
     */
    public boolean canRedo() {
        return !historyBack.isEmpty();
    }

    /**
     * 可以撤销
     *
     * @return
     */
    public boolean canUndo() {
        return !history.isEmpty();
    }

   @Override
        public final void afterTextChanged(Editable s) {
            if(mOnCanRedoAndCanUndoListener!=null){
                mOnCanRedoAndCanUndoListener.onCanRedoAndCanUndo(canRedo(),canUndo());
            }

            if (flag) return;
            if (s != editable) {
                editable = s;
                onEditableChanged(s);
            }
            PerformEdit.this.onTextChanged(s);
        }

我是这么加上的
